# Generated by Django 3.2 on 2023-07-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='admin_images')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('logo', models.ImageField(upload_to='logo')),
                ('location', models.CharField(max_length=100)),
                ('about_us', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.admin_1')),
                ('nurse', models.ManyToManyField(to='nurseApp.nurse')),
            ],
        ),
    ]
