# Generated by Django 3.2 on 2023-07-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('qualification', models.FileField(blank=True, null=True, upload_to='nurse_qualifications')),
                ('DoB', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nurse_images')),
                ('start_work', models.DateTimeField()),
                ('end_work', models.DateTimeField()),
            ],
        ),
    ]
