# Generated by Django 3.2 on 2023-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0002_auto_20230725_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='city',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
